name: Build

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use the latest stable Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.34

      - name: Install Dependencies
        run: bun install

      - name: Run Build
        run: bun run build